# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'integrityCheckDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IntegrityCheckDialog(object):
    def setupUi(self, IntegrityCheckDialog):
        IntegrityCheckDialog.setObjectName("IntegrityCheckDialog")
        IntegrityCheckDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        IntegrityCheckDialog.resize(579, 323)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(IntegrityCheckDialog.sizePolicy().hasHeightForWidth())
        IntegrityCheckDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(IntegrityCheckDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(IntegrityCheckDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.edtOriginalFile = QtWidgets.QLineEdit(IntegrityCheckDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtOriginalFile.sizePolicy().hasHeightForWidth())
        self.edtOriginalFile.setSizePolicy(sizePolicy)
        # self.edtOriginalFile.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edtOriginalFile.setObjectName("edtOriginalFile")
        self.horizontalLayout.addWidget(self.edtOriginalFile)
        self.btnOriginalFile = QtWidgets.QPushButton(IntegrityCheckDialog)
        self.btnOriginalFile.setObjectName("btnOriginalFile")
        self.horizontalLayout.addWidget(self.btnOriginalFile)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(IntegrityCheckDialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.edtHashValueOriginalFile = QtWidgets.QLineEdit(IntegrityCheckDialog)
        self.edtHashValueOriginalFile.setEnabled(True)
        self.edtHashValueOriginalFile.setObjectName("edtHashValueOriginalFile")
        self.horizontalLayout_4.addWidget(self.edtHashValueOriginalFile)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(IntegrityCheckDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.edtDecryptFile = QtWidgets.QLineEdit(IntegrityCheckDialog)
        self.edtDecryptFile.setObjectName("edtDecryptFile")
        self.horizontalLayout_2.addWidget(self.edtDecryptFile)
        self.btnDecryptFile = QtWidgets.QPushButton(IntegrityCheckDialog)
        self.btnDecryptFile.setObjectName("btnDecryptFile")
        self.horizontalLayout_2.addWidget(self.btnDecryptFile)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(IntegrityCheckDialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.edtHashValueDecryptFile = QtWidgets.QLineEdit(IntegrityCheckDialog)
        self.edtHashValueDecryptFile.setObjectName("edtHashValueDecryptFile")
        self.horizontalLayout_5.addWidget(self.edtHashValueDecryptFile)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnVerify = QtWidgets.QPushButton(IntegrityCheckDialog)
        self.btnVerify.setObjectName("btnVerify")
        self.horizontalLayout_3.addWidget(self.btnVerify)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(IntegrityCheckDialog)
        self.btnOriginalFile.clicked.connect(IntegrityCheckDialog.browseOriginalFile)
        self.btnDecryptFile.clicked.connect(IntegrityCheckDialog.browseDecryptFile)
        self.btnVerify.clicked.connect(IntegrityCheckDialog.verify)
        QtCore.QMetaObject.connectSlotsByName(IntegrityCheckDialog)

    def retranslateUi(self, IntegrityCheckDialog):
        _translate = QtCore.QCoreApplication.translate
        IntegrityCheckDialog.setWindowTitle(_translate("IntegrityCheckDialog", "Integrity Check"))
        self.label.setText(_translate("IntegrityCheckDialog", "Original File"))
        self.btnOriginalFile.setText(_translate("IntegrityCheckDialog", "browse"))
        self.label_3.setText(_translate("IntegrityCheckDialog", "Hash value"))
        self.label_2.setText(_translate("IntegrityCheckDialog", "Decrypt File"))
        self.btnDecryptFile.setText(_translate("IntegrityCheckDialog", "browse"))
        self.label_4.setText(_translate("IntegrityCheckDialog", "Hash value"))
        self.btnVerify.setText(_translate("IntegrityCheckDialog", "Verify"))

import resources_rc
