# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow_org.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import config

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(545, 572)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/image/lock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setStyleSheet("font: 11pt \"Ubuntu Mono\";")
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 3, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/image/symbol_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton.setIcon(icon1)
        self.addButton.setIconSize(QtCore.QSize(32, 32))
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_2.addWidget(self.addButton)
        self.encryptButton = QtWidgets.QPushButton(self.centralwidget)
        self.encryptButton.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/image/folder_locked32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.encryptButton.setIcon(icon2)
        self.encryptButton.setIconSize(QtCore.QSize(32, 32))
        self.encryptButton.setObjectName("encryptButton")
        self.horizontalLayout_2.addWidget(self.encryptButton)
        self.removeButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeButton.sizePolicy().hasHeightForWidth())
        self.removeButton.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/image/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeButton.setIcon(icon3)
        self.removeButton.setIconSize(QtCore.QSize(32, 32))
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout_2.addWidget(self.removeButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.aes = QtWidgets.QRadioButton(self.centralwidget)
        self.aes.setObjectName("aes")
        self.horizontalLayout_3.addWidget(self.aes)
        self.des = QtWidgets.QRadioButton(self.centralwidget)
        self.des.setObjectName("des")
        self.horizontalLayout_3.addWidget(self.des)
        self.rsa = QtWidgets.QRadioButton(self.centralwidget)
        self.rsa.setObjectName("rsa")
        self.horizontalLayout_3.addWidget(self.rsa)
        self.gridLayout.addLayout(self.horizontalLayout_3, 6, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 7, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.decryptButton = QtWidgets.QPushButton(self.centralwidget)
        self.decryptButton.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/image/open-key-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.decryptButton.setIcon(icon4)
        self.decryptButton.setIconSize(QtCore.QSize(32, 32))
        self.decryptButton.setObjectName("decryptButton")
        self.horizontalLayout.addWidget(self.decryptButton)
        self.integrityButton = QtWidgets.QPushButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/image/integrity.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.integrityButton.setIcon(icon5)
        self.integrityButton.setIconSize(QtCore.QSize(32, 32))
        self.integrityButton.setObjectName("integrityButton")
        self.horizontalLayout.addWidget(self.integrityButton)
        self.gridLayout.addLayout(self.horizontalLayout, 8, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 9, 0, 1, 1)
        self.copyright_label = QtWidgets.QLabel(self.centralwidget)
        self.copyright_label.setAlignment(QtCore.Qt.AlignCenter)
        self.copyright_label.setObjectName("copyright_label")
        self.gridLayout.addWidget(self.copyright_label, 10, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.addButton.clicked.connect(MainWindow.add_file)
        self.removeButton.clicked.connect(MainWindow.remove_file)
        self.encryptButton.clicked.connect(MainWindow.encrypt)
        self.listWidget.itemSelectionChanged.connect(MainWindow.selection_changed)
        self.decryptButton.clicked.connect(MainWindow.decrypt)
        self.pushButton.clicked.connect(MainWindow.browse)
        self.integrityButton.clicked.connect(MainWindow.integrityCheck)
        self.lineEdit.textChanged['QString'].connect(MainWindow.text_changed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        config.process_bar = self.progressBar

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BKU Encryption Tool"))
        self.label.setText(_translate("MainWindow", "Encryption Tool"))
        self.label_2.setText(_translate("MainWindow", "Please select one or more files"))
        self.addButton.setText(_translate("MainWindow", "Add File/Directory"))
        self.encryptButton.setText(_translate("MainWindow", "Encrypt"))
        self.removeButton.setText(_translate("MainWindow", "Remove"))
        self.aes.setText(_translate("MainWindow", "AES"))
        self.des.setText(_translate("MainWindow", "DES"))
        self.rsa.setText(_translate("MainWindow", "RSA"))
        self.pushButton.setText(_translate("MainWindow", "Browse"))
        self.decryptButton.setText(_translate("MainWindow", "Decrypt"))
        self.integrityButton.setText(_translate("MainWindow", "Integrity Check"))
        self.copyright_label.setText(_translate("MainWindow", "© Computer Science & Engineering BKU 2019"))
        self.aes.setChecked(True)

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

